font_family JetBrainsMono NF
font_size 10.5

cursor_shape block
cursor_stop_blinking_after 0
scrollback_lines 2000
copy_on_select yes
mouse_hide_wait 0
select_by_word_characters @-./_~?&=%+#a
enable_audio_bell no
bell_on_tab "🔔 "
remember_window_size  no
window_border_width 1pt
draw_minimal_borders yes
window_padding_width 10
inactive_text_alpha 0.6
hide_window_decorations yes
confirm_os_window_close 0
tab_bar_style powerline

# Deshabilitar el protocolo extendido de teclado (FIx doble enter en nvchad)
modify_font cell_height 0px
macos_option_as_alt no
kitty_mod ctrl+shift

# Esto es lo importante:
clear_all_shortcuts no
map enter send_text all \x0d
map backspace send_text all \x7f
